security:
    providers:
        doctrine_provider:
            entity:
                class: App\Entity\AdminUser
                property: username

    encoders:
        App\Entity\AdminUser: bcrypt
        App\Entity\FtpUser:
          id: App\Security\Md5PasswordEncoder

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            provider: doctrine_provider
            form_login:
                login_path: login
                check_path: login

            logout:
                path:   logout
                target: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
