twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version: 'v0.1-alpha8'
    form_themes:
        - 'bootstrap_4_layout.html.twig'