dashboard:
   path: /
   controller: App\Controller\DefaultController::dashboard

sessions:
   path: /sessions
   controller: App\Controller\DefaultController::activeSessions

users:
   path: /users
   controller: App\Controller\UserController::list

settings:
   path: /settings
   controller: App\Controller\SettingController::settings

new_user:
   path: /user/new
   controller: App\Controller\UserController::new

edit_user:
   path: /user/{user}/edit
   controller: App\Controller\UserController::edit

delete_user:
   path: /user/{user}/delete
   controller: App\Controller\UserController::delete

admin_users:
   path: /admin_users
   controller: App\Controller\AdminUserController::list

new_admin_user:
   path: /admin_user/new
   controller: App\Controller\AdminUserController::new

edit_admin_user:
   path: /admin_user/{user}/edit
   controller: App\Controller\AdminUserController::edit

login:
   path: /login
   controller: App\Controller\SecurityController::login

logout:
   path: /logout
   controller: App\Controller\SecurityController::logout
